language: ruby
bundler_args: --without development assets
rvm:
  - "2.0.0"

before_script:
  - mysql -e 'create database rhinobird_test;'

script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec spec

env:
  - DEV_DB_NAME=rhinobird DEV_DB_USER=root DEFAULT_HOST=http://localhost/ DEFAULT_SENDER=notify@rhinobird.tv HOST_PROTOCOL=http
