HOST: http://www.peepol.tv/

--- Peepol.tv ---

---
#API documentation

## Allowed HTTPs requests:

    POST   :   To create a resource
    GET    :   Get a resource or list of resources
    DELETE :   To delete resource
    PUT    :   To update a resource

## Description Of Usual Server Responses

- 200 `OK` - the request was successful.
- 201 `Created` - the request was successful and a resource was created.
- 204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
- 400 `Bad Request` - the request could not be understood or was missing required parameters.
- 401 `Unauthorized` - authentication failed or user doesn't have permissions for requested operation.
- 403 `Forbidden` - access denied.
- 404 `Not Found` - resource was not found
- 405 `Method Not Allowed` - requested method is not supported for resource.
---

--
Streams Resources
These are the video stream resources.

###Stream Properties
- id (string): Stream id (md5)
- url (string): Stream data source
- title (string): Title of the stream
- desc (string): Description
- channels (array): Channels list
- started_on (string): Stream started date
- thumbs: (hash) hash with thumb urls

Plus geoJSON properties ([geoJSON Specs](http://www.geojson.org/geojson-spec.html))

- type (string): "Feature"
- geometry (obj): Location geometry
- properties (obj): Extra properties for the location
--

List of streams
GET /streams
< 200
< Content-Type: application/json
[
    {
        "id": "ef18a7b75fc32246e46bd75ff910a582",
        "title": "Lollapalooza en Chile",
        "desc": "Excelent music!",
        "channels": [
            "5c3e0faaf75d891ef3fcc8ba54119e4c",
            "9e879d7d0dbd3e5df40fd77d0cef7182"
        ],
        "thumbs": {
            "small": "http://img.youtube.com/vi/fopr63yr3ps/default.jpg",            
            "medium": "http://img.youtube.com/vi/fopr63yr3ps/hqdefault.jpg",            
            "large": "http://img.youtube.com/vi/fopr63yr3ps/maxresdefault.jpg"
        },
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates":[
                -70.661713,
                -33.462666
            ]
        },
        "properties": {
            "geo_reference": "Parque O'higgins"
        },
        "started_on": "2012-01-23T12:00:00.000"
    },
    {
        "id": "51d1bc8ab4c5297843ea3f57b7800b30",
        "title": "No al lucro",
        "desc": "",
        "channels": [
            "5c3e0faaf75d891ef3fcc8ba54119e4c",
            "7652acc25ca9744695de61f3ae0b527b"
        ],
        "thumbs": {
            "small": "http://img.youtube.com/vi/VgPBse5BkA8/default.jpg",            
            "medium": "http://img.youtube.com/vi/VgPBse5BkA8/hqdefault.jpg",            
            "large": "http://img.youtube.com/vi/VgPBse5BkA8/maxresdefault.jpg"
        },
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates":[
                -70.652132,
                -33.44394
            ]
        },
        "properties": {
            "geo_reference": "Alameda"
        },
        "started_on": "2012-01-23T12:00:00.000"
    },
    {
        "id": "cf58e551d63525613465878c183266f5",
        "title": "El wanaco",
        "desc": "Esta pegando fuerte",
        "channels": [
            "9e879d7d0dbd3e5df40fd77d0cef7182"
        ],
        "thumbs": {
            "small": "http://img.youtube.com/vi/NR7JUM23WN8/default.jpg",            
            "medium": "http://img.youtube.com/vi/NR7JUM23WN8/hqdefault.jpg",            
            "large": "http://img.youtube.com/vi/NR7JUM23WN8/maxresdefault.jpg"
        },
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates":[
                -70.654106,
                -33.445301
            ]
        },
        "properties": {
            "geo_reference": "Nataniel Cox"
        },
        "started_on": "2012-01-23T12:00:00.000"
    },
    {
        "id": "ef18a7b75fc32246e46bd75ff910a582",
        "title": "Lollapalooza en Chile",
        "desc": "Excelent music!",
        "channels": [
            "5c3e0faaf75d891ef3fcc8ba54119e4c",
            "9e879d7d0dbd3e5df40fd77d0cef7182"
        ],
        "thumbs": {
            "small": "http://img.youtube.com/vi/fopr63yr3ps/default.jpg",            
            "medium": "http://img.youtube.com/vi/fopr63yr3ps/hqdefault.jpg",            
            "large": "http://img.youtube.com/vi/fopr63yr3ps/maxresdefault.jpg"
        },
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates":[
                -70.661713,
                -33.462666
            ]
        },
        "properties": {
            "geo_reference": "Parque O'higgins"
        },
        "started_on": "2012-01-23T12:00:00.000"
    },
    {
        "id": "51d1bc8ab4c5297843ea3f57b7800b30",
        "title": "No al lucro",
        "desc": "",
        "channels": [
            "5c3e0faaf75d891ef3fcc8ba54119e4c",
            "7652acc25ca9744695de61f3ae0b527b"
        ],
        "thumbs": {
            "small": "http://img.youtube.com/vi/VgPBse5BkA8/default.jpg",            
            "medium": "http://img.youtube.com/vi/VgPBse5BkA8/hqdefault.jpg",            
            "large": "http://img.youtube.com/vi/VgPBse5BkA8/maxresdefault.jpg"
        },
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates":[
                -70.652132,
                -33.44394
            ]
        },
        "properties": {
            "geo_reference": "Alameda"
        },
        "started_on": "2012-01-23T12:00:00.000"
    },
    {
        "id": "cf58e551d63525613465878c183266f5",
        "title": "El wanaco",
        "desc": "Esta pegando fuerte",
        "channels": [
            "9e879d7d0dbd3e5df40fd77d0cef7182"
        ],
        "thumbs": {
            "small": "http://img.youtube.com/vi/NR7JUM23WN8/default.jpg",            
            "medium": "http://img.youtube.com/vi/NR7JUM23WN8/hqdefault.jpg",            
            "large": "http://img.youtube.com/vi/NR7JUM23WN8/maxresdefault.jpg"
        },
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates":[
                -70.654106,
                -33.445301
            ]
        },
        "properties": {
            "geo_reference": "Nataniel Cox"
        },
        "started_on": "2012-01-23T12:00:00.000"
    }
]

Create a new stream
POST /streams
> Content-Type: application/json
> Accept: application/json
{
    "title": "Lollapalooza en Chile",
    "desc": "Excelent music!",
    "lon": -70.661713,
    "lat": -33.462666,
    "geo_reference": "Parque O'higgins"
}
< 201
< Content-Type: application/json
{
    "id": "812f16429fad2756693047f685b9956a",
    "title": "Lollapalooza en Chile",
    "desc": "Excelent music!",
    "channels": [],
    "thumbs": {
        "small": "http://img.youtube.com/vi/fopr63yr3ps/default.jpg",            
        "medium": "http://img.youtube.com/vi/fopr63yr3ps/hqdefault.jpg",            
        "large": "http://img.youtube.com/vi/fopr63yr3ps/maxresdefault.jpg"
    },
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates":[
            -70.661713,
            -33.462666
        ]
    },
    "properties": {
        "geo_reference": "Parque O'higgins"
    },
    "started_on": "2012-01-23T12:00:00.000"
}

Stream information
GET /streams/{id}
< 200
< Content-Type: application/json
{
    "id": "812f16429fad2756693047f685b9956a",
    "title": "Lollapalooza en Chile",
    "desc": "Excelent music!",
    "channels": [],
    "thumbs": {
        "small": "http://img.youtube.com/vi/fopr63yr3ps/default.jpg",            
        "medium": "http://img.youtube.com/vi/fopr63yr3ps/hqdefault.jpg",            
        "large": "http://img.youtube.com/vi/fopr63yr3ps/maxresdefault.jpg"
    },
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates":[
            -70.661713,
            -33.462666
        ]
    },
    "properties": {
        "geo_reference": "Parque O'higgins"
    },
    "started_on": "2012-01-23T12:00:00.000"
}

Deletes stream
DELETE /streams/{id}
< 204

--
Channels Resources
These are the channel resources.

###Channel Properties
- id (string): Channel id (md5)
- name (string): Unique name for the channel
- streams (array): List of streams
- streams_count: Count of streams in the channel
- created_at (string): Channel created date
--

List all the channels
GET /channels
< 200
[
    {
        "id": "5c3e0faaf75d891ef3fcc8ba54119e4c",
        "name": "LollapaloozaCL",
        "streams": [
            {
                "id": "51d1bc8ab4c5297843ea3f57b7800b30",
                "title": "Lollapalooza en Chile",
                "desc": "Excelent music!",
                "channels": [
                    "5c3e0faaf75d891ef3fcc8ba54119e4c",
                    "9e879d7d0dbd3e5df40fd77d0cef7182"
                ],
                "thumbs": {
                    "small": "http://img.youtube.com/vi/fopr63yr3ps/default.jpg",            
                    "medium": "http://img.youtube.com/vi/fopr63yr3ps/hqdefault.jpg",            
                    "large": "http://img.youtube.com/vi/fopr63yr3ps/maxresdefault.jpg"
                },
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates":[
                        -70.661713,
                        -33.462666
                    ]
                },
                "properties": {
                    "geo_reference": "Parque O'higgins"
                },
                "started_on": "2012-01-23T12:00:00.000"
            },
            {
                "id": "cf58e551d63525613465878c183266f5",
                "title": "Lollapalooza!",
                "desc": "Chancho en piedra",
                "channels": [
                    "5c3e0faaf75d891ef3fcc8ba54119e4c",
                    "7652acc25ca9744695de61f3ae0b527b"
                ],
                "thumbs": {
                    "small": "http://img.youtube.com/vi/NR7JUM23WN8/default.jpg",            
                    "medium": "http://img.youtube.com/vi/NR7JUM23WN8/hqdefault.jpg",            
                    "large": "http://img.youtube.com/vi/NR7JUM23WN8/maxresdefault.jpg"
                },
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates":[
                        -70.661713,
                        -33.462666
                    ]
                },
                "properties": {
                    "geo_reference": "Parque O'higgins"
                },
                "started_on": "2012-01-23T12:00:00.000"
            }
        ],
        "streams_count": 2,
        "created_at": "2012-01-23T12:00:00.000"
    },
    {
        "id": "9e879d7d0dbd3e5df40fd77d0cef7182",
        "name": "LosPinguinos",
        "streams": [
            {
                "id": "e407e83a8589e03ed88b83b143d76036",
                "title": "No al lucro",
                "desc": "",
                "channels": [
                    "9e879d7d0dbd3e5df40fd77d0cef7182",
                    "bb2ee58f56a6b8d9e560f40ae1b0b91f"
                ],
                "thumbs": {
                    "small": "http://img.youtube.com/vi/VgPBse5BkA8/default.jpg",            
                    "medium": "http://img.youtube.com/vi/VgPBse5BkA8/hqdefault.jpg",            
                    "large": "http://img.youtube.com/vi/VgPBse5BkA8/maxresdefault.jpg"
                },
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates":[
                        -70.652132,
                        -33.44394
                    ]
                },
                "properties": {
                    "geo_reference": "Alameda"
                },
                "started_on": "2012-01-23T12:00:00.000"
            }
        ],
        "streams_count": 1,
        "created_at": "2012-01-23T12:00:00.000"
    }
]

Create a new empty channel
POST /channels
> Content-Type: application/json
> Accept: application/json
{
    "name": "LollapaloozaCL"
}
< 201
< Content-Type: application/json
{
    "id": "5c3e0faaf75d891ef3fcc8ba54119e4c",
    "name": "LollapaloozaCL",
    "streams": [],
    "streams_count": 0,
    "created_at": "2012-01-23T12:00:00.000"
}

Channel information
GET /channels/{id}
< 200
< Content-Type: application/json
{
    "id": "5c3e0faaf75d891ef3fcc8ba54119e4c",
    "name": "LollapaloozaCL",
    "streams": [
        {
            "id": "51d1bc8ab4c5297843ea3f57b7800b30",
            "title": "Lollapalooza en Chile",
            "channels": [
                "5c3e0faaf75d891ef3fcc8ba54119e4c",
                "9e879d7d0dbd3e5df40fd77d0cef7182"
            ],
            "thumbs": {
                "small": "http://img.youtube.com/vi/fopr63yr3ps/default.jpg",            
                "medium": "http://img.youtube.com/vi/fopr63yr3ps/hqdefault.jpg",            
                "large": "http://img.youtube.com/vi/fopr63yr3ps/maxresdefault.jpg"
            },
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates":[
                    -70.661713,
                    -33.462666
                ]
            },
            "properties": {
                "geo_reference": "Parque O'higgins"
            },
            "started_on": "2012-01-23T12:00:00.000"
        },
        {
            "id": "cf58e551d63525613465878c183266f5",
            "title": "Lollapalooza!",
            "desc": "Chancho en piedra",
            "type": "Feature",
            "channels": [
                "5c3e0faaf75d891ef3fcc8ba54119e4c",
                "7652acc25ca9744695de61f3ae0b527b"
            ],
            "thumbs": {
                "small": "http://img.youtube.com/vi/NR7JUM23WN8/default.jpg",            
                "medium": "http://img.youtube.com/vi/NR7JUM23WN8/hqdefault.jpg",            
                "large": "http://img.youtube.com/vi/NR7JUM23WN8/maxresdefault.jpg"
            },
            "geometry": {
                "type": "Point",
                "coordinates":[
                    -70.661713,
                    -33.462666
                ]
            },
            "properties": {
                "geo_reference": "Parque O'higgins"
            },
            "started_on": "2012-01-23T12:00:00.000"
        }
    ],
    "streams_count": 3,
    "created_at": "2012-01-23T12:00:00.000"
}

Delete the channel
DELETE /channel/{id}
< 200
{ "status": "ok" }

Lists the current channel streams
GET /channels/{id}/streams
< 200
[
    {
        "id": "ef18a7b75fc32246e46bd75ff910a582",
        "title": "Lollapalooza en Chile",
        "desc": "Excelent music!",
        "channels":  [
            "5c3e0faaf75d891ef3fcc8ba54119e4c",
            "9e879d7d0dbd3e5df40fd77d0cef7182"
        ],
        "thumbs": {
            "small": "http://img.youtube.com/vi/fopr63yr3ps/default.jpg",            
            "medium": "http://img.youtube.com/vi/fopr63yr3ps/hqdefault.jpg",            
            "large": "http://img.youtube.com/vi/fopr63yr3ps/maxresdefault.jpg"
        },
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates":[
                -70.661713,
                -33.462666
            ]
        },
        "properties": {
            "geo_reference": "Parque O'higgins"
        },
        "started_on": "2012-01-23T12:00:00.000"
    },
    {
        "id": "51d1bc8ab4c5297843ea3f57b7800b30",
        "title": "Lollapalooza!",
        "desc": "Chancho en piedra",
        "channels": [
            "5c3e0faaf75d891ef3fcc8ba54119e4c",
            "7652acc25ca9744695de61f3ae0b527b"
        ],
        "thumbs": {
            "small": "http://img.youtube.com/vi/NR7JUM23WN8/default.jpg",            
            "medium": "http://img.youtube.com/vi/NR7JUM23WN8/hqdefault.jpg",            
            "large": "http://img.youtube.com/vi/NR7JUM23WN8/maxresdefault.jpg"
        },
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates":[
                -70.661713,
                -33.462666
            ]
        },
        "properties": {
            "geo_reference": "Parque O'higgins"
        },
        "started_on": "2012-01-23T12:00:00.000"
    }
]

--
Bonds Resource
This is the bonds resource definition.

###Channel Properties
- id (string): Bond UUID (md5)
- stream (string): UUID of the stream
- channel (string): UUID of the channel
- created_at (string): Channel created date
--

Lists bonds between streams and channels
GET /bonds
> Content-Type: application/json
> Accept: application/json
{
    "stream": "51d1bc8ab4c5297843ea3f57b7800b30"
}
< 200
{
    #TODO
}

Create a bond between a stream and a channel
POST /bonds
> Content-Type: application/json
> Accept: application/json
{
    "stream": "51d1bc8ab4c5297843ea3f57b7800b30",
    "channel":"bb2ee58f56a6b8d9e560f40ae1b0b91f"
}
< 201
{
    "id":"hdh373hjefw23823j823y32749j33hj28",
    "created_at": "2013-04-05 12:02:45",
    "stream":"51d1bc8ab4c5297843ea3f57b7800b30",
    "channel":"bb2ee58f56a6b8d9e560f40ae1b0b91f"
}

Removes a bond between channel and stream
DELETE /bonds/{id}
< 204
