FORMAT: 1A

HOST: http://api.rhinobird.tv

# Rhinobird.tv API

## Allowed HTTPs requests:

    POST   :   To create a resource
    GET    :   Get a resource or list of resources
    DELETE :   To delete resource
    PUT    :   To update a resource

## Description Of Usual Server Responses

- 200 `OK` - the request was successful.
- 201 `Created` - the request was successful and a resource was created.
- 204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
- 400 `Bad Request` - the request could not be understood or was missing required parameters.
- 401 `Unauthorized` - authentication failed or user doesn't have permissions for requested operation.
- 403 `Forbidden` - access denied.
- 404 `Not Found` - resource was not found
- 405 `Method Not Allowed` - requested method is not supported for resource.


# Group Streams
These are the video stream resources.

## Stream [/streams/{id}]
Properties:

- id (string): Stream id (md5)
- caption (string): Title of the stream, may have `#channels` inside
- live (boolean): flag for control the live status of the stream. Default: **false**
- channels (array): Channels list
- started_on (string): Stream started date
- thumbs: (hash) hash with thumb urls

Plus geoJSON properties ([geoJSON Specs](http://www.geojson.org/geojson-spec.html))

- type (string): "Feature"
- geometry (obj): Location geometry
- properties (obj): Extra properties for the location

+ Parameters
  + id (string) ... ID of the stream

+ Model (application/json)
  + Body

            {
                "id": "51d1bc8ab4c5297843ea3f57b7800b30",
                "caption": "No al lucro",
                "channel": {
                    "id": "5c3e0faaf75d891ef3fcc8ba54119e4c",
                    "name": "TheChannel"
                },
                "thumbs": {
                    "small": "http://img.youtube.com/vi/VgPBse5BkA8/default.jpg",
                    "medium": "http://img.youtube.com/vi/VgPBse5BkA8/hqdefault.jpg",
                    "large": "http://img.youtube.com/vi/VgPBse5BkA8/maxresdefault.jpg"
                },
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates":[
                        -70.647055,
                        -33.451534
                    ]
                },
                "properties": {
                    "geo_reference": "Alameda"
                },
                "tags": [
                  "grunge"
                ],
                "started_on": "2012-01-23T12:00:00.000"
            }

### Retrive a single stream [GET]
+ Response 200

    [Stream][]

### Delete a stream [DELETE]
+ Response 204

## Stream Collection [/streams{?q,offset,limit,live,force_check,lat,lng,range}]
+ Model (application/json)


    + Body

            [
                {
                    "id": "ef18a7b75fc32246e46bd75ff910a582",
                    "title": "#Lollapalooza en Chile",
                    "channel": {
                        "id": "5c3e0faaf75d891ef3fcc8ba54119e4c",
                        "name": "LollapaloozaCL"
                    },
                    "thumbs": {
                        "small": "http://img.youtube.com/vi/fopr63yr3ps/default.jpg",
                        "medium": "http://img.youtube.com/vi/fopr63yr3ps/hqdefault.jpg",
                        "large": "http://img.youtube.com/vi/fopr63yr3ps/maxresdefault.jpg"
                    },
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates":[
                            -70.661713,
                            -33.462666
                        ]
                    },
                    "properties": {
                        "geo_reference": "Parque O'higgins"
                    },
                    "tags": [
                      "concert", "rock", "grunge"
                    ],
                    "started_on": "2012-01-23T12:00:00.000"
                }
            ]

### Get all streams [GET]

+ Parameters
    + q (optional, string) ... query string to search.
    + offset (optional, integer) ... number of streams to skip.
    + limit (optional, integer) ... number of records to get
    + live (optional) ... flag to get live streams(cached)
    + force_check (optional) ... flag to force checking current live streams
    + lat (optional, float) ... latitude to search from
    + lng (optional, float) ... longitude to search from
    + range (optional, integer) ... range in KM for nearby streams

+ Response 200

    [Stream Collection][]

## Stream creation [/streams]

+ Model (application/json)

    [Stream][]

### Creates a new stream [POST]

+ Request (application/json)

        {
            "caption": "Lollapalooza en Chile",
            "lng": -70.661713,
            "lat": -33.462666,
            "geo_reference": "Parque O'higgins"
            "thumb" : "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoAAAAHgCAYAAAA10dzkAAAgAEl+s3wMFO7YfLcoEANpe6n1AiJ0rYHznnXdXW8qEUrT6/wOyX0OswSl+bQAAAABJRU5ErkJggg=="
        }

+ Response 201

    [Stream][]

## Play [/streams/{id}/play]
Increments the playcount for a stream

### Set as playing [PUT]

+ Response 200

## Tag [/streams/{id}/tag]
Tag to apply on a stream.

The resource has the following attributes:

- tag: (string) name of the tag


+ Parameters

    + id (string) ... ID of the stream to tag

+ Model (application/json)

### Adds a tag to a stream [POST]
+ Request (application/json)

        {
            "tag": "rock"
        }

+ Response 201

    [Stream][]

## Remove Tag [/streams/{id}/tag/{tag}]

+ Parameters

    + id (string) ... ID of the stream to tag
    + tag (string) ... name of the tag

### Removes a tag from a stream [DELETE]

+ Response 204

# Group Channels
This section groups channel resources.

## Channel Properties
- id (string): Channel id (md5)
- name (string): Unique name for the channel
- streams (array): List of streams
- streams_count: Count of streams in the channel
- created_at (string): Channel created date


## Channel [/channels/{id}]
A Channel can have many streams. Can be added through the API or in comments when creating/editing a stream.


+ Parameters

    + id (string) ... ID of the stream

+ Model (application/json)

    ```js
      {
            "id": "5c3e0faaf75d891ef3fcc8ba54119e4c",
            "name": "LollapaloozaCL",
            "streams": [],
            "streams_count": 0,
            "created_at": "2012-01-23T12:00:00.000"
        }
    ```

### Retrieve a Channel [GET]
Returns a specific Channel.

+ Response 200

    [Channel][]

### Delete a Channel [DELETE]
Deletes a channel

+ Response 204

## Channels Collection [/channels]
A collection of channels. `streams` embeds stream objects

+ Model (application/json)

    ```js
    [
        {
            "id": "5c3e0faaf75d891ef3fcc8ba54119e4c",
            "name": "LollapaloozaCL",
            "streams": [],
            "streams_count": 0,
            "created_at": "2012-01-23T12:00:00.000"
        },
        {
            "id": "5c3e0faaf75d891ef3fcc8ba54119e4c",
            "name": "ChannelLive",
            "streams": [],
            "streams_count": 0,
            "created_at": "2012-01-23T12:00:00.000"
        }
    ]
    ```

### Create a Channel [POST]
Creates a new channel.

+ Request

  ```js
        {
            "name": "LollapaloozaCL"
        }
    ```


+ Response 201

    [Channel][]

### Retrieve all Channels [GET]
Retrieves all channels.

+ Response 200

    [Channels Collection][]


## Streams of the channel [/channel/{id}/streams]

Returns the streams of the channel. The filter parameters of the `/streams`can also be used here.

+ Parameters

    + id (string) ... ID of the channel

### Get streams [GET]

+ Response 200

    [Stream Collection][]


# Group Users
This section groups channel resources.

## User Properties
- id (int): User ID
- email (string): email to register
- password (string): account desired password
- name (string): Name of account



## User [/users/{username}]
A single user resource

+ Parameters

    + username (string) ... Username to query

+ Model (application/json)

    ```js
        {
            "email": "sirius@rhinobird.tv",
            "name": "Sirius Black",
            "username": "sirius"
        }
    ```

### Retrieve a User [GET]
Returns a specific User.

+ Response 200

    [User][]

## Users Collection [/users]

### Create a User [POST]
Creates a new user.

+ Request

  ```js
        {
            "email": "sirius@rhinobird.tv",
            "password": "12345678",
            "name": "Sirius Black",
            "username": "sirius"
        }
    ```


+ Response 201

    [User][]


## User Password  [/users/password]
Adds password recovery options. The system sends an email to the registered email address
with a reset token.

### Ask password reset [POST]
Asks for a new password reset
+ Request

  ```js
        {
            "email": "sirius@rhinobird.tv"
        }
    ```

+ Response 200

## User Profile  [/users/profile]
Adds profile update to a logged user

### Update User [PUT]
Asks for a new password reset
+ Request

  ```js
        {
            "email": "sirius@rhinobird.tv",
            "username": "sirius"
        }
    ```

+ Response 200

  [User][]

### Confirm a new password [PUT]
Confirms new passwords
+ Request

  ```js
        {
            "token": "XXXXXXXXXXXXX",
            "password": "12345678",
            "password_confirmation": "12345678"
        }
    ```
+ Response 200


# Group Sessions
This resource handles authentication for users.

## Session Properties
- auth_token (string): Authentication token
- user: (object): Authenticated user


## Session Login [/sessions]
Session login

+ Model (application/json)

    ```js
        {
            "auth_token": "XXXXXXXXXXXXXXXXXXX",
            "user": {
                "email": "sirius@rhinobird.tv",
                "name": "Sirius Black",
                "username": "sirius"
            }
        }
    ```

### Login a user [POST]
Login with the required credentials
+ Request

  ```js
        {
            "email": "sirius@rhinobird.tv",
            "password": "12345678"
        }
    ```

+ Response 201

    [Session Login][]

## Session status [/sessions/current]

### Get current session [GET]
Returns the current session info, or `401` if not logged in

+ Response 201

    [Session Login][]

### Destroy session [DELETE]
Logs out the current user

+ Response 204



# Group VJ
This sections describes VJ session. A user can have many VJ sessions

## Vj Properties
- username:  owner of the vj
- channel: channel being vjed (channel object)
- token: The token to use for VJ connecting in the front end
- archived_url: full url of the archived session
- status: the current vj session status (**created, live, pending, archived**)
- picks: an array of the **picks** related to the VJ session

## Vj [/vjs/{id}]
Returns a vj records

+ Model (application/json)

        {
            "id": "9ee0b6f0e31dddbcd82d97fa19bfd070",
            "username": "siriusblack",
            "channel_name": "rock",
            "status": "live",
            "archived_url": null,
            "picks": [
                {
                    "id": "9ee0b6f0e31dddbcd82d97fa19bfd071",
                    "stream": {},
                    "active": "true",
                    "active_audio": "true"
                }
            ]
        }

### Get own VJ session [GET]
Returns a vj session by channel name for the current logged user

+ Response 200
    [Vj][]


### Update a VJ session [PUT]
Updates data of a VJ session
+ Request

        {
            "status": "live",
            "archived_url": ""
        }

+ Response 200
    [Vj][]

## Vj Collection [/vjs{?channel_name,created,live,pending,archived,page,per_page}]
Handle collections of Vj sessions

+ Parameters
    + channel_name (optional, string) ... channel_name to filter.
    + page (optional, integer) ... page number to get
    + per_page (optional, integer) ... number of results per page
    + created (optional, string) ... true/false
    + live (optional, string) ... true/false
    + pending (optional, string) ... true/false
    + archived (optional, string) ... true/false
    + stream_id (optional, string) ... stream ID inside of a VJ

+ Model (application/json)

        [
            {
                "id": "e491813b203a5cc841a65804cae88345"
                "username": "siriusblack",
                "channel_name": "rock",
                "status": "live",
                "archived_url": null,
                "picks": [
                    {
                        "id": "9ee0b6f0e31dddbcd82d97fa19bfd072",
                        "stream": {},
                        "active": "true",
                        "active_audio": "true"
                    }
                ]
            },
             {
                "id": "9ee0b6f0e31dddbcd82d97fa19bfd070"
                "username": "siriusblack",
                "channel_name": "rock",
                "status": "live",
                "archived_url": null,
                "picks": [
                    {
                        "id": "9ee0b6f0e31dddbcd82d97fa19bfd071"
                        "stream": {},
                        "active": "false",
                        "active_audio": "false"
                    }
                ]
            }
        ]

### Get all VJ sessions [GET]
Returns the vj sessions

+ Response 200
    [Vj Collection][]

### Create VJ session [POST]
Creates a new vj session for the logged user

+ Request

        {
            "channel_name": "rock",
        }

+ Response 201
  [Vj][]

## Vj Collection of a User [/users/{username}/vjs{?channel_name,created,live,pending,archived,page,per_page}]
Filter VJs by user. Same filter parameters as */vjs*

### Get VJ sessions [GET]
Return all the users VJ sessions

+ Response 200

    [Vj Collection][]


# Group Pick Resource
This section describes Picks. The Pick represents a stream that is in an active Vj session

## Pick Properties
- stream: the stream object that is in the VJ session
- active: Returns if the stream is the active stream in the pool

## Pick [/vjs/{id}/picks]
Manages a VJ's Pick

+ Model (application/json)

        {
            id: 'adbf5a778175ee757c34d0eba4e932bc',
            stream: {}
        }

### Create Pick [POST]
Pick another stream as inactive

+ Request

        {
            "stream_id": "2AFD",
            "active": true,
            "active_audio": false
        }

+ Response 200

    [Pick][]

## Pick [/picks/{id}]

### Retrive a single pick [GET]

+ Response 200
    [Pick][]


### Update pick [PUT]
Activates a different stream. If the stream is offline, the API will return status code `409 Conflict`.

+ Request

        {
            "active": true,
            "active_audio": false
        }

+ Response 200

    [Pick][]


### Remove a stream from the pool [DELETE]
Remove a stream

+ Response 204


